name: Deutsche Telekom Workflow

on:
  push:
    branches:
      - main
      - chat_feature

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Deploy to Azure Web App
      run: |
        sed -i 's/\$GREETING_NAME/${{ secrets.GREETING_NAME }}/g' index.html
        sed -i 's/API_KEY_PLACEHOLDER/${{ secrets.API_KEY }}/g' api/chat.php
        chmod +x ./az-deploy.sh
        ./az-deploy.sh
      env:
        AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
        AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
        AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        REPO_URL: ${{ secrets.REPO_URL }}
        GREETING_NAME: ${{ secrets.GREETING_NAME }}
        API_KEY: ${{ secrets.API_KEY }}
